run:
  deadline: 1m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable-all: true
  disable:
    - exhaustive
    - exhaustivestruct
    - funlen
    - gci
    - gochecknoglobals
    - golint
    - interfacer
    - lll
    - maligned
    - nlreturn
    - paralleltest
    - scopelint
    - testpackage
    - wsl
  fast: false
